name       : libexif
version    : 0.6.21
release    : 5
source     :
    - https://10gbps-io.dl.sourceforge.net/project/libexif/libexif/0.6.21/libexif-0.6.21.tar.bz2 : 16cdaeb62eb3e6dfab2435f7d7bccd2f37438d21c5218ec4e58efa9157d4d41a
homepage   : https://sourceforge.net/projects/libexif/
license    : LGPL-2.0
component  : desktop.library
emul32     : yes
summary    : EXIF tag parsing library
description: |
    Most digital cameras produce EXIF files, which are JPEG files with extra tags that contain information about the image. The EXIF library allows you to parse an EXIF file and read the data from those tags.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2016-6328.patch
    %patch -p1 < $pkgfiles/security/CVE-2017-7544.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
