name        : libexif
version     : 0.6.21
release     : 3
source      :
    - http://sourceforge.net/projects/libexif/files/libexif/0.6.21/libexif-0.6.21.tar.bz2/download : 16cdaeb62eb3e6dfab2435f7d7bccd2f37438d21c5218ec4e58efa9157d4d41a
homepage    : http://sourceforge.net/projects/libexif/
license     : GPL-3.0
component   : desktop.library
summary     : EXIF tag parsing library
description : |
    EXIF tag parsing library
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
