name       : libexif
version    : 0.6.22
release    : 6
source     :
    - https://github.com/libexif/libexif/releases/download/libexif-0_6_22-release/libexif-0.6.22.tar.xz : 5048f1c8fc509cc636c2f97f4b40c293338b6041a5652082d5ee2cf54b530c56
homepage   : https://sourceforge.net/projects/libexif/
license    : LGPL-2.0-or-later
component  : desktop.library
emul32     : yes
summary    : EXIF tag parsing library
description: |
    Most digital cameras produce EXIF files, which are JPEG files with extra tags that contain information about the image. The EXIF library allows you to parse an EXIF file and read the data from those tags.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
